//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Checkin terminal
{
	public virtual object Location
	{
		get;
		set;
	}

	public virtual void Process card()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Display()
	{
		throw new System.NotImplementedException();
	}

}

