//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Course Info
{
	public virtual object Faculty
	{
		get;
		set;
	}

	public virtual object Time
	{
		get;
		set;
	}

	public virtual void Update course data()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Get course()
	{
		throw new System.NotImplementedException();
	}

}

