//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class device list
{
	public virtual object location
	{
		get;
		set;
	}

	public virtual object addres
	{
		get;
		set;
	}

	public virtual User Interface User Interface
	{
		get;
		set;
	}

	public virtual void view device()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete device()
	{
		throw new System.NotImplementedException();
	}

	public virtual void add device()
	{
		throw new System.NotImplementedException();
	}

}

