//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Faculty courses record
{
	public virtual object course records
	{
		get;
		set;
	}

	public virtual void get records()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update faculty data()
	{
		throw new System.NotImplementedException();
	}

}

