//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Retrieve data
{
	public virtual void get courses()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get checkin()
	{
		throw new System.NotImplementedException();
	}

}

