//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Student attendance history
{
	public virtual object attendance record
	{
		get;
		set;
	}

	public virtual Checkin terminal Checkin terminal
	{
		get;
		set;
	}

	public virtual Student checkin Student checkin
	{
		get;
		set;
	}

	public virtual void get attendance()
	{
		throw new System.NotImplementedException();
	}

	public virtual void associated class()
	{
		throw new System.NotImplementedException();
	}

	public virtual void save()
	{
		throw new System.NotImplementedException();
	}

	public virtual void update attendance()
	{
		throw new System.NotImplementedException();
	}

}

