//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Student registration
{
	public virtual object Courses
	{
		get;
		set;
	}

	public virtual object .Student number string
	{
		get;
		set;
	}

	public virtual Checkin terminal Checkin terminal
	{
		get;
		set;
	}

	public virtual void Find courses()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get records()
	{
		throw new System.NotImplementedException();
	}

	public virtual void updates student data()
	{
		throw new System.NotImplementedException();
	}

}

