//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Student checkin
{
	public virtual Checkin terminal Checkin terminal
	{
		get;
		set;
	}

	public virtual void .update manual entry()
	{
		throw new System.NotImplementedException();
	}

	public virtual void display()
	{
		throw new System.NotImplementedException();
	}

}

