//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User Interface
{
	public virtual {
		get;
		set;
	}

	public virtual Export Export
	{
		get;
		set;
	}

	public virtual View class control View class control
	{
		get;
		set;
	}

	public virtual Faculty courses record Faculty courses record
	{
		get;
		set;
	}

	public virtual void select view()
	{
		throw new System.NotImplementedException();
	}

	public virtual void select course()
	{
		throw new System.NotImplementedException();
	}

	public virtual void select view classes()
	{
		throw new System.NotImplementedException();
	}

	public virtual void enter login()
	{
		throw new System.NotImplementedException();
	}

	public virtual void export()
	{
		throw new System.NotImplementedException();
	}

	public virtual void override checkin()
	{
		throw new System.NotImplementedException();
	}

	public virtual void add device()
	{
		throw new System.NotImplementedException();
	}

	public virtual void delete device()
	{
		throw new System.NotImplementedException();
	}

	public virtual void view device()
	{
		throw new System.NotImplementedException();
	}

}

