//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class User directory
{
	public virtual object User profile
	{
		get;
		set;
	}

	public virtual void .get user()
	{
		throw new System.NotImplementedException();
	}

	public virtual void get student number()
	{
		throw new System.NotImplementedException();
	}

}

